defaults:  
  # Directory Configs
  scratch_dir: "./scratch_dir/"
  datadir: null # Set automatically using the suite

  # General Configs
  seed: 0
  deterministic_run: False
  compile: True
  device: 'cuda:0'
  debug: False
  precision: 32

  # Wandb configs
  use_wandb: True
  wandb_entity: '504985967' # Top level name
  wandb_project: null
  wandb_exp_name: null

  # Run Params
  viz_expert_buffer: False
  update_dp: False
  train_dp_mppi: False
  state_only: False
  generate_highres_eval: False

  # Data params
  num_exp_trajs: 1000 # To be specified when starting a new run
  num_exp_val_trajs: 100
  normalize_state_actions: False
  image_size: 128
  obs_horizon: 2 # Number of observations to stack
  action_horizon: 2 # Number of actions to take
  pred_horizon: 8 # Number of actions to stack
  num_buffer_transitions: 100000
  state_dim: -1 # To be set when loading expert data
  action_dim: -1 # To be set when loading expert data

  # Evaluation
  eval_num_runs: 50
  visualize_eval: False # Store videos of all eval runs
  log_every: 50

  # Environment
  task: 'libero_90__1-40' # To be specified when starting a new run
  num_envs: 10
  time_limit: -1 # overwritten for each env, defined below
  high_res_render: False # If true, videos will be stored in high resolution
  highres_img_size: 1024
  

  # Training
  batch_size: 16
  batch_length: 32
  model_lr: 1e-4
  opt_eps: 1e-8
  grad_clip: 1000
  opt: 'adam'
  discount: 0.99
  discount_lambda: 0.95
  imag_horizon: 7

  # DP Config
  dp:
    train_steps: 240000
    batch_size: 256
    lr: 0.0001
    max_iterations: 120000
    log_freq: 100
    eval_freq: 5000
    schedule_freq: 1
    devices: 1
    device: 'cuda:0'
    seed: 292285
    action_space: 'deltas'
    ac_chunk: 8
    img_chunk: 2
    num_cams: 1
    use_obs: False
    train_transform: 'gpu_medium'
    debug: False
    print_config: False
    pretrained_ckpt: ""
    shared_mlp: []
    use_if_ckpt_present: False
    quantize_image_features: True
  

robomimic:
  done_mode: 1 # can be 0, 1, 2
  action_repeat: 1
  shape_rewards: True
  
  dp:
    shared_mlp: []
    train_steps: 24000
    eval_freq: 12000

  env_max_steps:
    {lift: 1e5, can: 5e5, square: 5e5}
  env_time_limits:
    {lift: 100, can: 200, square: 200}

robocasa:
  done_mode: 1 # can be 0, 1, 2
  action_repeat: 3
  
  dp:
    shared_mlp: []
    train_steps: 24000
    eval_freq: 12000

  env_max_steps:
    { 
      stack: 3e5, door: 1e5, bread: 3e5,
      cereal: 5e5, nutassemblyround: 5e5, 
      breadcanfixed: 5e5, breadcanrandom: 5e5, 
    }

  env_time_limits:
    {stack: 150, door: 200, bread: 200,
    cereal: 150, nutassemblyround: 300,
    breadcanfixed: 400, breadcanrandom: 400}

maniskill:
  action_repeat: 2
  image_size: 64
  use_cpu_env: True
  
  dp:
    shared_mlp: []
    train_steps: 24000
    eval_freq: 12000
    
  env_max_steps:
    {pullcube: 1e5, liftpeg: 3e5, pokecube: 3e5}
  env_time_limits:
    {pullcube: 50, liftpeg: 150, pokecube: 100}



debug:
  debug: True
  logdir: "debug_logs"
  pretrain: 1
  prefill: 1
  batch_size: 4
  batch_length: 8
  num_exp_trajs: 5
  num_exp_val_trajs: 1
  eval_episode_num: 0
  eval_num_runs: 3
  steps_per_batch: 10
  train_ratio: 50
  num_envs: 3
  num_buffer_transitions: 50
  visualize_eval: False

  dp:
    train_steps: 10
    eval_freq: 10
  
  use_wandb: False

  

  